models:
  - model: "D:/Uni/Masterarbeit Code/jakob_finetuning/finetuned_models/meta_llama_full_colab_remerge_2"
    parameters:
      weight: 0.75  
  - model: "ai4bharat/hercule-fr"
    parameters:
      weight: 0.25  

merge_method: linear
dtype: bfloat16