models:
  - model: "D:/Uni/Masterarbeit Code/jakob_finetuning/finetuned_models/meta_llama_full_colab_remerge_2"
    parameters:
      weight: 1.0
      density: 1.0
  - model: "Nos-PT/Llama-Carvalho-PT"
    parameters:
      weight: 0.846
      density: 1.0

base_model: "unsloth/Meta-Llama-3.1-8B-Instruct"

merge_method: dare_ties
dtype: bfloat16

parameters:
  lambda: 1.0
  rescale: false